name: Auto Merge to Dev

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Vérifier les approbations
        id: check_approvals
        run: |
          APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '[.reviews[].state] | map(select(. == "APPROVED")) | length')
          echo "Nombre d'approbations: $APPROVALS"
          if [ "$APPROVALS" -ge 2 ]; then
            echo "approved=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fusionner la PR si approuvée
        if: env.approved == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Envoyer une notification sur Discord
        if: env.approved == 'true'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Bot",
                 "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                 "embeds": [{
                   "title": "🚀 Merge effectué vers `dev` !",
                   "description": "**PR #${{ github.event.pull_request.number }}** - [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) a été fusionnée.",
                   "color": 65280
                 }]
               }' ${{ secrets.DISCORD_WEBHOOK_URL }}
